# Generated by Django 3.2.7 on 2021-09-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
